/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HeadingJumpFixPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/funding.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var FUNDING_URL = "https://buymeacoffee.com/k_tech_studio";
var PLUGIN_NAME = "Heading Jump Fix";

// src/funding.ts
var FundingModal = class extends import_obsidian.Modal {
  constructor(app, kind, version) {
    super(app);
    this.kind = kind;
    this.version = version;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText(PLUGIN_NAME);
    const heading = this.kind === "install" ? "Thanks for installing!" : `Updated to ${this.version}`;
    contentEl.createEl("h3", { text: heading });
    contentEl.createEl("p", {
      text: this.kind === "install" ? "Heading Jump Fix auto-corrects scroll after outline clicks. If it saves you a second click, consider supporting development." : "Thanks for updating. New versions keep outline jumps reliable. If this plugin helps your workflow, consider supporting development."
    });
    const actions = contentEl.createDiv({ cls: "modal-button-container" });
    const coffeeBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: "Buy Me a Coffee"
    });
    coffeeBtn.addEventListener("click", () => {
      window.open(FUNDING_URL, "_blank");
      this.close();
    });
    const laterBtn = actions.createEl("button", { text: "Maybe later" });
    laterBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
function openFundingModal(app, kind, version) {
  new FundingModal(app, kind, version).open();
}

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: true,
  outlineFix: true,
  retryDelayMs: 250,
  retryCount: 1
};
var HeadingJumpFixSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Heading Jump Fix" });
    new import_obsidian2.Setting(containerEl).setName("Enable plugin").setDesc("Master switch for scroll correction.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Outline click fix").setDesc("Retry scroll after clicking a heading in the Outline sidebar.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.outlineFix).onChange(async (value) => {
        this.plugin.settings.outlineFix = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Retry delay (ms)").setDesc("Wait before correcting scroll (default 250).").addText(
      (text) => text.setPlaceholder("250").setValue(String(this.plugin.settings.retryDelayMs)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!Number.isFinite(parsed) || parsed < 0) return;
        this.plugin.settings.retryDelayMs = parsed;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Retry count").setDesc("Number of correction passes after outline click (default 1).").addText(
      (text) => text.setPlaceholder("1").setValue(String(this.plugin.settings.retryCount)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!Number.isFinite(parsed) || parsed < 0) return;
        this.plugin.settings.retryCount = parsed;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Support" });
    new import_obsidian2.Setting(containerEl).setName("Buy Me a Coffee").setDesc("Support K-Tech Studio development.").addButton(
      (button) => button.setButtonText("Buy Me a Coffee").onClick(() => {
        window.open(FUNDING_URL, "_blank");
      })
    );
  }
};

// src/heading-resolver.ts
function normalizeHeadingText(text) {
  return text.trim().replace(/\s+/g, " ");
}
function resolveHeading(app, target) {
  var _a;
  const cache = app.metadataCache.getFileCache(target.file);
  const headings = cache == null ? void 0 : cache.headings;
  if (!(headings == null ? void 0 : headings.length)) return null;
  const normalized = normalizeHeadingText(target.headingText);
  const matches = headings.filter(
    (h) => h.level === target.level && normalizeHeadingText(h.heading) === normalized
  );
  if (!matches.length) return null;
  const occurrence = (_a = target.occurrenceIndex) != null ? _a : 0;
  const heading = matches[Math.min(occurrence, matches.length - 1)];
  return { line: heading.position.start.line, heading };
}
function findHeadingAtLine(app, file, line) {
  const cache = app.metadataCache.getFileCache(file);
  const headings = cache == null ? void 0 : cache.headings;
  if (!(headings == null ? void 0 : headings.length)) return null;
  let best = null;
  for (const h of headings) {
    const hLine = h.position.start.line;
    if (hLine <= line && (!best || hLine > best.position.start.line)) {
      best = h;
    }
  }
  if (!best) return null;
  return { line: best.position.start.line, heading: best };
}
function countPriorMatchingHeadings(item, headingText, level, outlineRoot) {
  const items = Array.from(
    outlineRoot.querySelectorAll(".tree-item")
  );
  const index = items.indexOf(item);
  if (index < 0) return 0;
  let count = 0;
  for (let i = 0; i < index; i++) {
    const other = items[i];
    if (getOutlineItemLevel(other) === level && getOutlineItemText(other) === headingText) {
      count++;
    }
  }
  return count;
}
function getOutlineItemLevel(item) {
  for (const el of [item, item.querySelector(".tree-item-self")]) {
    if (!el) continue;
    const modLevel = Array.from(el.classList).find(
      (c) => c.startsWith("mod-heading-")
    );
    if (modLevel) {
      const n = parseInt(modLevel.replace("mod-heading-", ""), 10);
      if (Number.isFinite(n)) return Math.min(Math.max(n, 1), 6);
    }
  }
  const self = item.querySelector(".tree-item-self");
  const indentLevels = self == null ? void 0 : self.querySelectorAll(".tree-item-indent-level");
  if (indentLevels && indentLevels.length > 0) {
    return Math.min(indentLevels.length, 6);
  }
  const indent = item.querySelector(".tree-item-indent");
  if (indent) {
    const levels = indent.querySelectorAll(".tree-item-indent-level");
    if (levels.length > 0) return Math.min(levels.length, 6);
  }
  return 1;
}
function getOutlineItemText(item) {
  var _a;
  const inner = item.querySelector(".tree-item-inner");
  return normalizeHeadingText((_a = inner == null ? void 0 : inner.textContent) != null ? _a : "");
}

// src/jump-engine.ts
function scrollLineIntoView(editor, line) {
  const pos = { line, ch: 0 };
  editor.setCursor(pos);
  editor.scrollIntoView({ from: pos, to: pos }, true);
}
function doubleRafScroll(editor, line) {
  return new Promise((resolve) => {
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        scrollLineIntoView(editor, line);
        resolve();
      });
    });
  });
}
function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
async function reliableJump(editor, resolved, options) {
  if (!editor) {
    return { ok: false, line: -1, retries: 0, reason: "no-editor" };
  }
  if (!resolved) {
    return { ok: false, line: -1, retries: 0, reason: "not-found" };
  }
  const { line } = resolved;
  const passes = Math.max(1, options.retryCount + 1);
  for (let i = 0; i < passes; i++) {
    if (i > 0 && options.retryDelayMs > 0) {
      await delay(options.retryDelayMs);
    }
    scrollLineIntoView(editor, line);
    await doubleRafScroll(editor, line);
  }
  return { ok: true, line, retries: Math.max(0, passes - 1) };
}

// src/outline-hook.ts
var import_obsidian3 = require("obsidian");
var OUTLINE_SELECTORS = {
  leaf: '.workspace-leaf-content[data-type="outline"]',
  treeItem: ".tree-item",
  treeItemSelf: ".tree-item-self",
  treeItemInner: ".tree-item-inner"
};
var OutlineHook = class {
  constructor(app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
    this.handler = null;
    this.pendingTimer = null;
  }
  register() {
    this.handler = (event) => {
      void this.onClick(event);
    };
    document.addEventListener("click", this.handler, true);
  }
  unregister() {
    if (this.handler) {
      document.removeEventListener("click", this.handler, true);
      this.handler = null;
    }
    this.clearPending();
  }
  clearPending() {
    if (this.pendingTimer !== null) {
      clearTimeout(this.pendingTimer);
      this.pendingTimer = null;
    }
  }
  onClick(event) {
    const settings = this.getSettings();
    if (!settings.enabled || !settings.outlineFix) return;
    const target = event.target;
    if (!(target instanceof Element)) return;
    const outlineLeaf = target.closest(OUTLINE_SELECTORS.leaf);
    if (!outlineLeaf) return;
    const treeItemSelf = target.closest(OUTLINE_SELECTORS.treeItemSelf);
    if (!treeItemSelf) return;
    const treeItem = treeItemSelf.closest(OUTLINE_SELECTORS.treeItem);
    if (!treeItem || !(treeItem instanceof HTMLElement)) return;
    const headingText = getOutlineItemText(treeItem);
    if (!headingText) return;
    const level = getOutlineItemLevel(treeItem);
    const occurrenceIndex = countPriorMatchingHeadings(
      treeItem,
      headingText,
      level,
      outlineLeaf
    );
    const file = this.app.workspace.getActiveFile();
    if (!file) return;
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!(markdownView == null ? void 0 : markdownView.editor)) return;
    this.clearPending();
    this.pendingTimer = setTimeout(() => {
      this.pendingTimer = null;
      void this.performJump(file, headingText, level, occurrenceIndex);
    }, settings.retryDelayMs);
  }
  async performJump(file, headingText, level, occurrenceIndex) {
    const settings = this.getSettings();
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    const editor = markdownView == null ? void 0 : markdownView.editor;
    if (!editor) return;
    const resolved = resolveHeading(this.app, {
      file,
      headingText,
      level,
      occurrenceIndex
    });
    await reliableJump(editor, resolved, {
      retryCount: settings.retryCount,
      retryDelayMs: settings.retryDelayMs
    });
  }
};

// src/storage.ts
function parseStorage(raw) {
  if (!raw || typeof raw !== "object") {
    return { settings: { ...DEFAULT_SETTINGS } };
  }
  const data = raw;
  if ("settings" in data && data.settings && typeof data.settings === "object") {
    return {
      settings: Object.assign({}, DEFAULT_SETTINGS, data.settings),
      lastSeenVersion: typeof data.lastSeenVersion === "string" ? data.lastSeenVersion : void 0
    };
  }
  return {
    settings: Object.assign({}, DEFAULT_SETTINGS, data),
    lastSeenVersion: void 0
  };
}
function toStorage(settings, lastSeenVersion) {
  return { settings, lastSeenVersion };
}

// src/main.ts
var HeadingJumpFixPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.outlineHook = null;
  }
  async onload() {
    await this.loadSettings();
    this.outlineHook = new OutlineHook(this.app, () => this.settings);
    this.outlineHook.register();
    this.addSettingTab(new HeadingJumpFixSettingTab(this.app, this));
    this.addCommand({
      id: "jump-to-heading-at-cursor",
      name: "Jump to heading at cursor line reliably",
      editorCallback: (editor, view) => {
        void this.jumpAtCursor(editor, view.file);
      }
    });
    await this.maybeShowFundingModal();
  }
  onunload() {
    var _a;
    (_a = this.outlineHook) == null ? void 0 : _a.unregister();
    this.outlineHook = null;
  }
  async loadSettings() {
    const storage = parseStorage(await this.loadData());
    this.settings = storage.settings;
    this.lastSeenVersion = storage.lastSeenVersion;
  }
  async saveSettings() {
    await this.saveData(toStorage(this.settings, this.lastSeenVersion));
  }
  async maybeShowFundingModal() {
    const currentVersion = this.manifest.version;
    if (this.lastSeenVersion === currentVersion) return;
    const kind = this.lastSeenVersion ? "update" : "install";
    window.setTimeout(() => {
      openFundingModal(this.app, kind, currentVersion);
    }, 800);
    this.lastSeenVersion = currentVersion;
    await this.saveSettings();
  }
  async jumpAtCursor(editor, file) {
    if (!this.settings.enabled || !file) return;
    const cursor = editor.getCursor();
    const resolved = findHeadingAtLine(this.app, file, cursor.line);
    await reliableJump(editor, resolved, {
      retryCount: this.settings.retryCount,
      retryDelayMs: this.settings.retryDelayMs
    });
  }
};
