/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HeadingJumpFixPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/funding.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var FUNDING_URL = "https://buymeacoffee.com/k_tech_studio";
var PLUGIN_NAME = "Heading Jump Fix";

// src/funding.ts
var FundingModal = class extends import_obsidian.Modal {
  constructor(app, kind, version) {
    super(app);
    this.kind = kind;
    this.version = version;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText(PLUGIN_NAME);
    const heading = this.kind === "install" ? "Thanks for installing!" : `Updated to ${this.version}`;
    contentEl.createEl("h3", { text: heading });
    contentEl.createEl("p", {
      text: this.kind === "install" ? "Heading Jump Fix auto-corrects scroll after outline clicks. If it saves you a second click, consider supporting development." : "Thanks for updating. New versions keep outline jumps reliable. If this plugin helps your workflow, consider supporting development."
    });
    const actions = contentEl.createDiv({ cls: "modal-button-container" });
    const coffeeBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: "Buy Me a Coffee"
    });
    coffeeBtn.addEventListener("click", () => {
      window.open(FUNDING_URL, "_blank");
      this.close();
    });
    const laterBtn = actions.createEl("button", { text: "Maybe later" });
    laterBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
function openFundingModal(app, kind, version) {
  new FundingModal(app, kind, version).open();
}

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  enabled: true,
  outlineFix: true,
  bodyLinkFix: true,
  linkPaneFix: true,
  retryDelayMs: 250,
  retryCount: 1,
  scrollToCenter: true,
  overrideThemeScroll: true,
  debugLog: false
};
var HeadingJumpFixSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [
      {
        name: "Enable plugin",
        desc: "Master switch for scroll correction.",
        control: {
          type: "toggle",
          key: "enabled",
          defaultValue: DEFAULT_SETTINGS.enabled
        }
      },
      {
        name: "Outline click fix",
        desc: "Retry scroll after clicking a heading in the Outline sidebar.",
        control: {
          type: "toggle",
          key: "outlineFix",
          defaultValue: DEFAULT_SETTINGS.outlineFix
        }
      },
      {
        name: "Wikilink click fix",
        desc: "Retry scroll after in-note [[wikilink#heading]] clicks.",
        control: {
          type: "toggle",
          key: "bodyLinkFix",
          defaultValue: DEFAULT_SETTINGS.bodyLinkFix
        }
      },
      {
        name: "Link pane click fix",
        desc: "Retry scroll after heading clicks in Outgoing links / Backlinks.",
        control: {
          type: "toggle",
          key: "linkPaneFix",
          defaultValue: DEFAULT_SETTINGS.linkPaneFix
        }
      },
      {
        name: "Retry delay (ms)",
        desc: "Wait before correcting scroll (default 250).",
        control: {
          type: "number",
          key: "retryDelayMs",
          min: 0,
          defaultValue: DEFAULT_SETTINGS.retryDelayMs
        }
      },
      {
        name: "Retry count",
        desc: "Number of correction passes. Later passes wait longer (backoff).",
        control: {
          type: "number",
          key: "retryCount",
          min: 0,
          defaultValue: DEFAULT_SETTINGS.retryCount
        }
      },
      {
        name: "Scroll heading to center",
        desc: "Place the heading near the middle of the editor. Off = align to the top.",
        control: {
          type: "toggle",
          key: "scrollToCenter",
          defaultValue: DEFAULT_SETTINGS.scrollToCenter
        }
      },
      {
        name: "Override theme scroll-behavior",
        desc: "Force instant editor scrolling so theme smooth-scroll does not miss the heading.",
        control: {
          type: "toggle",
          key: "overrideThemeScroll",
          defaultValue: DEFAULT_SETTINGS.overrideThemeScroll
        }
      },
      {
        name: "Debug log",
        desc: "Write jump details to the developer console (no network).",
        control: {
          type: "toggle",
          key: "debugLog",
          defaultValue: DEFAULT_SETTINGS.debugLog
        }
      },
      {
        type: "group",
        heading: "Support",
        items: [
          {
            name: "Buy Me a Coffee",
            desc: "Support K-Tech Studio development.",
            action: () => {
              window.open(FUNDING_URL, "_blank");
            }
          }
        ]
      }
    ];
  }
  getControlValue(key) {
    return this.plugin.settings[key];
  }
  async setControlValue(key, value) {
    this.plugin.settings[key] = value;
    await this.plugin.saveSettings();
  }
  /** Fallback for Obsidian versions older than 1.13.0. */
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Enable plugin").setDesc("Master switch for scroll correction.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enabled).onChange(async (value) => {
        this.plugin.settings.enabled = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Outline click fix").setDesc("Retry scroll after clicking a heading in the Outline sidebar.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.outlineFix).onChange(async (value) => {
        this.plugin.settings.outlineFix = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Wikilink click fix").setDesc("Retry scroll after in-note [[wikilink#heading]] clicks.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.bodyLinkFix).onChange(async (value) => {
        this.plugin.settings.bodyLinkFix = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Link pane click fix").setDesc("Retry scroll after heading clicks in Outgoing links / Backlinks.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.linkPaneFix).onChange(async (value) => {
        this.plugin.settings.linkPaneFix = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Retry delay (ms)").setDesc("Wait before correcting scroll (default 250).").addText(
      (text) => text.setPlaceholder("250").setValue(String(this.plugin.settings.retryDelayMs)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!Number.isFinite(parsed) || parsed < 0) return;
        this.plugin.settings.retryDelayMs = parsed;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Retry count").setDesc("Number of correction passes. Later passes wait longer (backoff).").addText(
      (text) => text.setPlaceholder("1").setValue(String(this.plugin.settings.retryCount)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!Number.isFinite(parsed) || parsed < 0) return;
        this.plugin.settings.retryCount = parsed;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Scroll heading to center").setDesc(
      "Place the heading near the middle of the editor. Off = align to the top."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.scrollToCenter).onChange(async (value) => {
        this.plugin.settings.scrollToCenter = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Override theme scroll-behavior").setDesc(
      "Force instant editor scrolling so theme smooth-scroll does not miss the heading."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.overrideThemeScroll).onChange(async (value) => {
        this.plugin.settings.overrideThemeScroll = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Debug log").setDesc("Write jump details to the developer console (no network).").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.debugLog).onChange(async (value) => {
        this.plugin.settings.debugLog = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Support").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Buy Me a Coffee").setDesc("Support K-Tech Studio development.").addButton(
      (button) => button.setButtonText("Buy Me a Coffee").onClick(() => {
        window.open(FUNDING_URL, "_blank");
      })
    );
  }
};

// src/heading-resolver.ts
function normalizeHeadingText(text) {
  return text.trim().replace(/\s+/g, " ");
}
function resolveHeading(app, target) {
  var _a;
  const cache = app.metadataCache.getFileCache(target.file);
  const headings = cache == null ? void 0 : cache.headings;
  if (!(headings == null ? void 0 : headings.length)) return null;
  const normalized = normalizeHeadingText(target.headingText);
  const matches = headings.filter(
    (h) => h.level === target.level && normalizeHeadingText(h.heading) === normalized
  );
  if (!matches.length) return null;
  const occurrence = (_a = target.occurrenceIndex) != null ? _a : 0;
  const heading = matches[Math.min(occurrence, matches.length - 1)];
  return { line: heading.position.start.line, heading };
}
function resolveHeadingByText(app, file, headingText, occurrenceIndex = 0) {
  const cache = app.metadataCache.getFileCache(file);
  const headings = cache == null ? void 0 : cache.headings;
  if (!(headings == null ? void 0 : headings.length)) return null;
  const normalized = normalizeHeadingText(headingText);
  const matches = headings.filter(
    (h) => normalizeHeadingText(h.heading) === normalized
  );
  if (!matches.length) return null;
  const heading = matches[Math.min(occurrenceIndex, matches.length - 1)];
  return { line: heading.position.start.line, heading };
}
function findHeadingAtLine(app, file, line) {
  const cache = app.metadataCache.getFileCache(file);
  const headings = cache == null ? void 0 : cache.headings;
  if (!(headings == null ? void 0 : headings.length)) return null;
  let best = null;
  for (const h of headings) {
    const hLine = h.position.start.line;
    if (hLine <= line && (!best || hLine > best.position.start.line)) {
      best = h;
    }
  }
  if (!best) return null;
  return { line: best.position.start.line, heading: best };
}
function countPriorMatchingHeadings(item, headingText, level, outlineRoot) {
  const items = Array.from(outlineRoot.querySelectorAll(".tree-item"));
  const index = items.indexOf(item);
  if (index < 0) return 0;
  let count = 0;
  for (let i = 0; i < index; i++) {
    const other = items[i];
    if (getOutlineItemLevel(other) === level && getOutlineItemText(other) === headingText) {
      count++;
    }
  }
  return count;
}
function getOutlineItemLevel(item) {
  for (const el of [item, item.querySelector(".tree-item-self")]) {
    if (!el) continue;
    const modLevel = Array.from(el.classList).find(
      (c) => c.startsWith("mod-heading-")
    );
    if (modLevel) {
      const n = parseInt(modLevel.replace("mod-heading-", ""), 10);
      if (Number.isFinite(n)) return Math.min(Math.max(n, 1), 6);
    }
  }
  const self = item.querySelector(".tree-item-self");
  const indentLevels = self == null ? void 0 : self.querySelectorAll(".tree-item-indent-level");
  if (indentLevels && indentLevels.length > 0) {
    return Math.min(indentLevels.length, 6);
  }
  const indent = item.querySelector(".tree-item-indent");
  if (indent) {
    const levels = indent.querySelectorAll(".tree-item-indent-level");
    if (levels.length > 0) return Math.min(levels.length, 6);
  }
  return 1;
}
function getOutlineItemText(item) {
  var _a;
  const inner = item.querySelector(".tree-item-inner");
  return normalizeHeadingText((_a = inner == null ? void 0 : inner.textContent) != null ? _a : "");
}

// src/debug.ts
var PREFIX = "[Heading Jump Fix]";
function debugLog(enabled, message, extra) {
  if (!enabled) return;
  if (extra !== void 0) {
    console.log(PREFIX, message, extra);
  } else {
    console.log(PREFIX, message);
  }
}

// src/jump-engine.ts
function jumpOptionsFromSettings(settings) {
  return {
    retryCount: settings.retryCount,
    retryDelayMs: settings.retryDelayMs,
    debugLog: settings.debugLog,
    scrollToCenter: settings.scrollToCenter
  };
}
function getCm(editor) {
  var _a;
  const rec = editor;
  return (_a = rec.cm) != null ? _a : null;
}
function isHeadingVisible(editor, line) {
  var _a;
  const cm = getCm(editor);
  if (!(cm == null ? void 0 : cm.coordsAtPos) || !((_a = cm.state) == null ? void 0 : _a.doc) || !cm.scrollDOM) return null;
  try {
    const docLine = cm.state.doc.line(line + 1);
    const coords = cm.coordsAtPos(docLine.from);
    if (!coords) return false;
    const box = cm.scrollDOM.getBoundingClientRect();
    const margin = 8;
    return coords.top >= box.top - margin && coords.bottom <= box.bottom + margin;
  } catch (e) {
    return null;
  }
}
function scrollLineIntoView(editor, line, center) {
  const pos = { line, ch: 0 };
  editor.setCursor(pos);
  editor.scrollIntoView({ from: pos, to: pos }, center);
}
function doubleRafScroll(editor, line, center) {
  return new Promise((resolve) => {
    window.requestAnimationFrame(() => {
      window.requestAnimationFrame(() => {
        scrollLineIntoView(editor, line, center);
        resolve();
      });
    });
  });
}
function delay(ms) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}
function backoffMs(baseMs, extraPassIndex) {
  return baseMs * Math.pow(2, extraPassIndex);
}
async function reliableJump(editor, resolved, options) {
  const log = !!options.debugLog;
  const center = options.scrollToCenter !== false;
  if (!editor) {
    const result2 = {
      ok: false,
      line: -1,
      retries: 0,
      reason: "no-editor"
    };
    debugLog(log, "jump failed", result2);
    return result2;
  }
  if (!resolved) {
    const result2 = {
      ok: false,
      line: -1,
      retries: 0,
      reason: "not-found"
    };
    debugLog(log, "jump failed", result2);
    return result2;
  }
  const { line } = resolved;
  const passes = Math.max(1, options.retryCount + 1);
  let visible = null;
  for (let i = 0; i < passes; i++) {
    if (i > 0 && options.retryDelayMs > 0) {
      await delay(backoffMs(options.retryDelayMs, i - 1));
    }
    debugLog(log, "scroll pass", {
      line,
      heading: resolved.heading.heading,
      pass: i + 1,
      of: passes,
      center
    });
    scrollLineIntoView(editor, line, center);
    await doubleRafScroll(editor, line, center);
    visible = isHeadingVisible(editor, line);
    debugLog(log, "viewport check", { line, visible });
    if (visible === true) break;
  }
  const result = {
    ok: true,
    line,
    retries: Math.max(0, passes - 1),
    visible
  };
  debugLog(log, "jump result", result);
  return result;
}

// src/outline-hook.ts
var import_obsidian3 = require("obsidian");
var OUTLINE_SELECTORS = {
  leaf: '.workspace-leaf-content[data-type="outline"]',
  treeItem: ".tree-item",
  treeItemSelf: ".tree-item-self",
  treeItemInner: ".tree-item-inner"
};
var OutlineHook = class {
  constructor(app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
    this.handler = null;
    this.pendingTimer = null;
    this.attached = /* @__PURE__ */ new Set();
  }
  register(plugin) {
    this.handler = (event) => {
      void this.onClick(event);
    };
    this.attach(document);
    plugin.registerEvent(
      this.app.workspace.on("window-open", (_win, window2) => {
        this.attach(window2.document);
      })
    );
    plugin.registerEvent(
      this.app.workspace.on("window-close", (_win, window2) => {
        this.detach(window2.document);
      })
    );
  }
  unregister() {
    for (const doc of [...this.attached]) {
      this.detach(doc);
    }
    this.handler = null;
    this.clearPending();
  }
  attach(doc) {
    if (!this.handler || this.attached.has(doc)) return;
    doc.addEventListener("click", this.handler, true);
    this.attached.add(doc);
  }
  detach(doc) {
    if (!this.handler || !this.attached.has(doc)) return;
    doc.removeEventListener("click", this.handler, true);
    this.attached.delete(doc);
  }
  clearPending() {
    if (this.pendingTimer !== null) {
      window.clearTimeout(this.pendingTimer);
      this.pendingTimer = null;
    }
  }
  onClick(event) {
    const settings = this.getSettings();
    if (!settings.enabled || !settings.outlineFix) return;
    const target = event.target;
    if (!(target instanceof Element)) return;
    const outlineLeaf = target.closest(OUTLINE_SELECTORS.leaf);
    if (!outlineLeaf) return;
    const treeItemSelf = target.closest(OUTLINE_SELECTORS.treeItemSelf);
    if (!treeItemSelf) return;
    const treeItem = treeItemSelf.closest(OUTLINE_SELECTORS.treeItem);
    if (!(treeItem == null ? void 0 : treeItem.instanceOf(HTMLElement))) return;
    const headingText = getOutlineItemText(treeItem);
    if (!headingText) return;
    const level = getOutlineItemLevel(treeItem);
    const occurrenceIndex = countPriorMatchingHeadings(
      treeItem,
      headingText,
      level,
      outlineLeaf
    );
    const file = this.app.workspace.getActiveFile();
    if (!file) return;
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!(markdownView == null ? void 0 : markdownView.editor)) return;
    this.clearPending();
    debugLog(settings.debugLog, "outline click", {
      headingText,
      level,
      occurrenceIndex,
      file: file.path,
      delayMs: settings.retryDelayMs
    });
    this.pendingTimer = window.setTimeout(() => {
      this.pendingTimer = null;
      void this.performJump(file, headingText, level, occurrenceIndex);
    }, settings.retryDelayMs);
  }
  async performJump(file, headingText, level, occurrenceIndex) {
    const settings = this.getSettings();
    const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    const editor = markdownView == null ? void 0 : markdownView.editor;
    if (!editor) return;
    const resolved = resolveHeading(this.app, {
      file,
      headingText,
      level,
      occurrenceIndex
    });
    await reliableJump(
      editor,
      resolved,
      jumpOptionsFromSettings(settings)
    );
  }
};

// src/link-hook.ts
var import_obsidian4 = require("obsidian");
var LINK_PANE_LEAF = '.workspace-leaf-content[data-type="outgoing-link"], .workspace-leaf-content[data-type="backlink"]';
var OUTLINE_LEAF = '.workspace-leaf-content[data-type="outline"]';
var LinkHook = class {
  constructor(app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
    this.handler = null;
    this.pendingTimer = null;
    this.attached = /* @__PURE__ */ new Set();
  }
  register(plugin) {
    this.handler = (event) => {
      this.onClick(event);
    };
    this.attach(document);
    plugin.registerEvent(
      this.app.workspace.on("window-open", (_win, window2) => {
        this.attach(window2.document);
      })
    );
    plugin.registerEvent(
      this.app.workspace.on("window-close", (_win, window2) => {
        this.detach(window2.document);
      })
    );
  }
  unregister() {
    for (const doc of [...this.attached]) {
      this.detach(doc);
    }
    this.handler = null;
    this.clearPending();
  }
  attach(doc) {
    if (!this.handler || this.attached.has(doc)) return;
    doc.addEventListener("click", this.handler, true);
    this.attached.add(doc);
  }
  detach(doc) {
    if (!this.handler || !this.attached.has(doc)) return;
    doc.removeEventListener("click", this.handler, true);
    this.attached.delete(doc);
  }
  clearPending() {
    if (this.pendingTimer !== null) {
      window.clearTimeout(this.pendingTimer);
      this.pendingTimer = null;
    }
  }
  onClick(event) {
    var _a, _b;
    const settings = this.getSettings();
    if (!settings.enabled) return;
    const target = event.target;
    if (!(target instanceof Element)) return;
    if (target.closest(OUTLINE_LEAF)) return;
    const inPane = !!target.closest(LINK_PANE_LEAF);
    if (inPane && !settings.linkPaneFix) return;
    if (!inPane && !settings.bodyLinkFix) return;
    const href = findInternalHeadingHref(target);
    if (!href) return;
    const parsed = (0, import_obsidian4.parseLinktext)(href);
    const headingText = headingFromSubpath(parsed.subpath);
    if (!headingText) return;
    const sourcePath = (_b = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path) != null ? _b : "";
    this.clearPending();
    debugLog(settings.debugLog, inPane ? "link pane click" : "wikilink click", {
      href,
      path: parsed.path,
      headingText,
      delayMs: settings.retryDelayMs
    });
    this.pendingTimer = window.setTimeout(() => {
      this.pendingTimer = null;
      void this.performJump(parsed.path, headingText, sourcePath);
    }, settings.retryDelayMs);
  }
  async performJump(linkpath, headingText, sourcePath) {
    const settings = this.getSettings();
    const file = resolveDestFile(this.app, linkpath, sourcePath);
    if (!file) return;
    const markdownView = findMarkdownView(this.app, file);
    const editor = markdownView == null ? void 0 : markdownView.editor;
    if (!editor) return;
    const resolved = resolveHeadingByText(this.app, file, headingText);
    await reliableJump(editor, resolved, jumpOptionsFromSettings(settings));
  }
};
function headingFromSubpath(subpath) {
  if (!subpath || subpath.startsWith("#^")) return null;
  const raw = subpath.startsWith("#") ? subpath.slice(1) : subpath;
  if (!raw) return null;
  try {
    return decodeURIComponent(raw).trim();
  } catch (e) {
    return raw.trim();
  }
}
function findInternalHeadingHref(start) {
  let cur = start;
  for (let i = 0; i < 10 && cur; i++) {
    const dataHref = cur.getAttribute("data-href");
    if (dataHref && dataHref.includes("#") && !dataHref.includes("#^")) {
      return dataHref;
    }
    const href = cur.getAttribute("href");
    if (href && href.includes("#") && !href.includes("#^") && (cur.classList.contains("internal-link") || cur.getAttribute("data-href") !== null)) {
      return href;
    }
    cur = cur.parentElement;
  }
  return null;
}
function resolveDestFile(app, linkpath, sourcePath) {
  var _a;
  if (!linkpath) return app.workspace.getActiveFile();
  return (_a = app.metadataCache.getFirstLinkpathDest(linkpath, sourcePath)) != null ? _a : app.workspace.getActiveFile();
}
function findMarkdownView(app, file) {
  var _a, _b;
  const leaves = app.workspace.getLeavesOfType("markdown");
  for (const leaf of leaves) {
    const view = leaf.view;
    if (view instanceof import_obsidian4.MarkdownView && ((_a = view.file) == null ? void 0 : _a.path) === file.path) {
      return view;
    }
  }
  const active = app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
  if (((_b = active == null ? void 0 : active.file) == null ? void 0 : _b.path) === file.path) return active;
  return active;
}

// src/storage.ts
function parseStorage(raw) {
  if (!raw || typeof raw !== "object") {
    return { settings: { ...DEFAULT_SETTINGS } };
  }
  const data = raw;
  if ("settings" in data && data.settings && typeof data.settings === "object") {
    return {
      settings: Object.assign({}, DEFAULT_SETTINGS, data.settings),
      lastSeenVersion: typeof data.lastSeenVersion === "string" ? data.lastSeenVersion : void 0
    };
  }
  return {
    settings: Object.assign({}, DEFAULT_SETTINGS, data),
    lastSeenVersion: void 0
  };
}
function toStorage(settings, lastSeenVersion) {
  return { settings, lastSeenVersion };
}

// src/theme-scroll.ts
var INSTANT_SCROLL_BODY_CLASS = "heading-jump-fix-instant-scroll";
function applyInstantScrollOverride(app, enabled) {
  for (const doc of collectDocuments(app)) {
    doc.body.classList.toggle(INSTANT_SCROLL_BODY_CLASS, enabled);
  }
}
function collectDocuments(app) {
  const docs = /* @__PURE__ */ new Set([document]);
  app.workspace.iterateAllLeaves((leaf) => {
    const win = leaf.view.containerEl.win;
    if (win == null ? void 0 : win.document) docs.add(win.document);
  });
  return [...docs];
}

// src/main.ts
var HeadingJumpFixPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.outlineHook = null;
    this.linkHook = null;
  }
  async onload() {
    await this.loadSettings();
    this.applyThemeScrollOverride();
    this.registerEvent(
      this.app.workspace.on("window-open", () => {
        this.applyThemeScrollOverride();
      })
    );
    this.outlineHook = new OutlineHook(this.app, () => this.settings);
    this.outlineHook.register(this);
    this.linkHook = new LinkHook(this.app, () => this.settings);
    this.linkHook.register(this);
    this.addSettingTab(new HeadingJumpFixSettingTab(this.app, this));
    this.addCommand({
      id: "jump-to-heading-at-cursor",
      name: "Jump to heading at cursor line reliably",
      editorCallback: (editor, view) => {
        void this.jumpAtCursor(editor, view.file);
      }
    });
    await this.maybeShowFundingModal();
  }
  onunload() {
    var _a, _b;
    applyInstantScrollOverride(this.app, false);
    (_a = this.outlineHook) == null ? void 0 : _a.unregister();
    this.outlineHook = null;
    (_b = this.linkHook) == null ? void 0 : _b.unregister();
    this.linkHook = null;
  }
  async loadSettings() {
    const storage = parseStorage(await this.loadData());
    this.settings = storage.settings;
    this.lastSeenVersion = storage.lastSeenVersion;
  }
  async saveSettings() {
    await this.saveData(toStorage(this.settings, this.lastSeenVersion));
    this.applyThemeScrollOverride();
  }
  applyThemeScrollOverride() {
    applyInstantScrollOverride(this.app, this.settings.overrideThemeScroll);
  }
  async maybeShowFundingModal() {
    const currentVersion = this.manifest.version;
    if (this.lastSeenVersion === currentVersion) return;
    const kind = this.lastSeenVersion ? "update" : "install";
    window.setTimeout(() => {
      openFundingModal(this.app, kind, currentVersion);
    }, 800);
    this.lastSeenVersion = currentVersion;
    await this.saveSettings();
  }
  async jumpAtCursor(editor, file) {
    if (!this.settings.enabled || !file) return;
    const cursor = editor.getCursor();
    const resolved = findHeadingAtLine(this.app, file, cursor.line);
    debugLog(this.settings.debugLog, "command jump", {
      file: file.path,
      cursorLine: cursor.line
    });
    await reliableJump(
      editor,
      resolved,
      jumpOptionsFromSettings(this.settings)
    );
  }
};
